disabled_rules:
    - trailing_whitespace
    - implicit_getter
excluded:
- Carthage
- Pods
- CoreCatowserTests/GeneratedMocks

identifier_name:
    min_length: 1 # warning
nesting:
    type_level: 3

opt_in_rules:
    - force_unwrapping

force_unwrapping: error
unneeded_break_in_switch: error

