# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
# source 'https://github.com/100mango/SwiftCssParser.git'

target 'Cotton' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cotton
  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SwiftLint', '~> 0.33.0'
end

target 'CoreBrowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreBrowser
  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SwiftLint', '~> 0.33.0'
end

target 'JSPlugins' do
  use_frameworks!

  pod 'SwiftSoup', '~> 2.3.2'
  # pod 'SwiftCssParser'
  pod 'SwiftLint', '~> 0.33.0'
  pod 'ReactiveSwift', '~> 6.0.0'
end

target 'JSPluginsTests' do
  use_frameworks!

# Probably it is not right way of fixing
# unit tests only should require main framework 
# as a dependency which is JSPlugins.framework
  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SWXMLHash', '~> 5.0.0'
  pod 'SwiftLint', '~> 0.33.0'
  pod 'SwiftSoup', '~> 2.3.2'
end

target 'HttpKitTests' do
  use_frameworks!

# Probably it is not right way of fixing
# unit tests only should require main framework 
# as a dependency which is JSPlugins.framework
  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SwiftLint', '~> 0.33.0'
end

target 'CoreBrowserTests' do
  use_frameworks!

# Probably it is not right way of fixing
# unit tests only should require main framework 
# as a dependency which is JSPlugins.framework
  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SwiftLint', '~> 0.33.0'
end

target 'HttpKit' do
  use_frameworks!

  pod 'SwiftLint', '~> 0.33.0'
end

target 'ReactiveHttpKit' do
  use_frameworks!

  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SwiftLint', '~> 0.33.0'
end

target 'BrowserNetworking' do
  use_frameworks!

  pod 'ReactiveSwift', '~> 6.0.0'
  pod 'SWXMLHash', '~> 5.0.0'
end

deployment_target = '12.0'

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
