# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'catowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for catowser
  pod 'SnapKit', '~>4.2.0'
  pod 'Alamofire', '~> 4.8'
  pod 'ReactiveSwift', '~> 3.0'
  pod 'SwiftLint'
  pod 'AlamofireImage', '~> 3.5'
end

target 'CoreBrowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreBrowser
  pod 'Alamofire', '~> 4.8'
  pod 'ReactiveSwift', '~> 3.0'
  pod 'SwiftLint'
end

target 'JSPlugins' do
  use_frameworks!

  pod 'SwiftSoup'
end

