# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'catowser' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for catowser
  pod 'SnapKit', '~>4.2.0'
  pod 'Alamofire', '~> 4.7'
end
