sources:
  - ../CoreBrowser/Tabs
templates:
  - ./Sourcery/Templates/AutoMockable.stencil
output:
    ./GeneratedMocks
args:
# Imports do not work for some reason
    # import: "ReactiveSwift"
    # import: "CottonCoreBaseKit"
    # import: "CoreBrowser"
