disabled_rules:
    - trailing_whitespace
    - implicit_getter
    - line_length
    - file_length
excluded:
    - Carthage
    - Pods
    - CottonDataTests/GeneratedMocks
    - DerivedData
    - SourcePackages

identifier_name:
    min_length: 1 # warning
nesting:
    type_level: 3
type_name:
    min_length: 1 # to allow usual short Generic names

opt_in_rules:
    - force_unwrapping

force_unwrapping: error
unneeded_break_in_switch: error

