# configs for Swift
tap "cotton-user/cotton-brew-taps"
brew 'cotton-user/cotton-brew-taps/sourcery'
# sourcery line is replaced on install command in different make script
brew 'cotton-user/cotton-brew-taps/swiftlint'
brew 'cotton-user/cotton-brew-taps/xcode-kotlin'
# mint needed to install SwiftyMocky
brew 'cotton-user/cotton-brew-taps/mint'
brew 'cotton-user/cotton-brew-taps/gradle@7'
# configs for Kotlin
brew 'cotton-user/cotton-brew-taps/ktlint'
brew 'cotton-user/cotton-brew-taps/openjdk'