# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Cotton-iOS

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened]
    paths:
      - "catowseriOS/.swiftlint.yml"
      - "**/*.swift"
      - "cotton-base/**/*.kt"

jobs:
  lint-ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: SwiftLint (Only files changed in the PR)
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
        DIFF_BASE: ${{ github.base_ref }}
      with:
        args: --force-exclude --strict --config catowseriOS/.swiftlint.yml
  lint-kotlin:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v1"
  build-ios:
    needs: [lint-ios, lint-kotlin]
    runs-on: macos-latest
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin
    steps:
    - uses: actions/cache@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    - uses: actions/cache@v3
      with:
        path: catowseriOS/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
            ${{ runner.os }}-spm-
    - uses: actions/checkout@v3
    - name: Build
      run: make github-workflow-ios
