# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Cotton-iOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin
    steps:
    - uses: actions/cache@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    - uses: actions/cache@v3
      with:
        path: catowseriOS/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
            ${{ runner.os }}-spm-
    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        cache-version: 1
    - name: GitHub Action for SwiftLint with --strict
      uses: norio-nomura/action-swiftlint@3.2.0
      with:
        args: --strict
    - uses: actions/checkout@v3
    - name: Build
      run: make github-workflow-ios
