name: Cotton-iOS

on:
  pull_request:
    branches: [ "master" ]
    types: [opened, reopened]
    paths:
      - "catowseriOS/.swiftlint.yml"
      - "catowseriOS/**/*.swift"
      - "cotton-base/**/*.kt"

jobs:
  lint-ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: SwiftLint (all swift files)
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --force-exclude --config catowseriOS/.swiftlint.yml
  lint-kotlin-cotton-base:
    runs-on: ubuntu-latest
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
      - name: "ktlint"
        uses: "vroy/gha-kotlin-linter@v4"
        with:
          args: --editorconfig=cotton-base/.editorconfig --disabled_rules=trailing-comma,standard:trailing-comma-on-call-site,standard:trailing-comma-on-declaration-site,standard:colon-spacing
          patterns: cotton-base/**/*.kt
  build-ios:
    needs: [lint-ios, lint-kotlin-cotton-base]
    runs-on: macos-latest
    env:
      MINT_PATH: .mint/lib
      MINT_LINK_PATH: .mint/bin
    steps:
    - uses: actions/cache@v3
      with:
        path: .mint
        key: ${{ runner.os }}-mint-${{ hashFiles('**/Mintfile') }}
        restore-keys: |
          ${{ runner.os }}-mint-
    - uses: actions/cache@v3
      with:
        path: catowseriOS/SourcePackages
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
            ${{ runner.os }}-spm-
    - uses: actions/checkout@v3
    - name: Build
      run: make github-workflow-ios
